/**
 */
package intelligentMobility.provider;

import intelligentMobility.util.IntelligentMobilityAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class IntelligentMobilityItemProviderAdapterFactory extends IntelligentMobilityAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection supportedTypes = new ArrayList();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public IntelligentMobilityItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.MobilitySystem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MobilitySystemItemProvider mobilitySystemItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.MobilitySystem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createMobilitySystemAdapter() {
		if (mobilitySystemItemProvider == null) {
			mobilitySystemItemProvider = new MobilitySystemItemProvider(this);
		}

		return mobilitySystemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Driver_Profile} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Driver_ProfileItemProvider driver_ProfileItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Driver_Profile}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDriver_ProfileAdapter() {
		if (driver_ProfileItemProvider == null) {
			driver_ProfileItemProvider = new Driver_ProfileItemProvider(this);
		}

		return driver_ProfileItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Vehicle_Configuration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Vehicle_ConfigurationItemProvider vehicle_ConfigurationItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Vehicle_Configuration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createVehicle_ConfigurationAdapter() {
		if (vehicle_ConfigurationItemProvider == null) {
			vehicle_ConfigurationItemProvider = new Vehicle_ConfigurationItemProvider(this);
		}

		return vehicle_ConfigurationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Environment_Background} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Environment_BackgroundItemProvider environment_BackgroundItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Environment_Background}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createEnvironment_BackgroundAdapter() {
		if (environment_BackgroundItemProvider == null) {
			environment_BackgroundItemProvider = new Environment_BackgroundItemProvider(this);
		}

		return environment_BackgroundItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Driver_Preference} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Driver_PreferenceItemProvider driver_PreferenceItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Driver_Preference}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDriver_PreferenceAdapter() {
		if (driver_PreferenceItemProvider == null) {
			driver_PreferenceItemProvider = new Driver_PreferenceItemProvider(this);
		}

		return driver_PreferenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Knowledge_and_Skill} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Knowledge_and_SkillItemProvider knowledge_and_SkillItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Knowledge_and_Skill}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createKnowledge_and_SkillAdapter() {
		if (knowledge_and_SkillItemProvider == null) {
			knowledge_and_SkillItemProvider = new Knowledge_and_SkillItemProvider(this);
		}

		return knowledge_and_SkillItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Driver_Emotion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Driver_EmotionItemProvider driver_EmotionItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Driver_Emotion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDriver_EmotionAdapter() {
		if (driver_EmotionItemProvider == null) {
			driver_EmotionItemProvider = new Driver_EmotionItemProvider(this);
		}

		return driver_EmotionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Driving_Behaviour} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Driving_BehaviourItemProvider driving_BehaviourItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Driving_Behaviour}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDriving_BehaviourAdapter() {
		if (driving_BehaviourItemProvider == null) {
			driving_BehaviourItemProvider = new Driving_BehaviourItemProvider(this);
		}

		return driving_BehaviourItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Normal_Behaviour} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Normal_BehaviourItemProvider normal_BehaviourItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Normal_Behaviour}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createNormal_BehaviourAdapter() {
		if (normal_BehaviourItemProvider == null) {
			normal_BehaviourItemProvider = new Normal_BehaviourItemProvider(this);
		}

		return normal_BehaviourItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Following} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FollowingItemProvider followingItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Following}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createFollowingAdapter() {
		if (followingItemProvider == null) {
			followingItemProvider = new FollowingItemProvider(this);
		}

		return followingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.LaneChanging} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LaneChangingItemProvider laneChangingItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.LaneChanging}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLaneChangingAdapter() {
		if (laneChangingItemProvider == null) {
			laneChangingItemProvider = new LaneChangingItemProvider(this);
		}

		return laneChangingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Abnormal_Behaviour} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Abnormal_BehaviourItemProvider abnormal_BehaviourItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Abnormal_Behaviour}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAbnormal_BehaviourAdapter() {
		if (abnormal_BehaviourItemProvider == null) {
			abnormal_BehaviourItemProvider = new Abnormal_BehaviourItemProvider(this);
		}

		return abnormal_BehaviourItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Forward} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ForwardItemProvider forwardItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Forward}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createForwardAdapter() {
		if (forwardItemProvider == null) {
			forwardItemProvider = new ForwardItemProvider(this);
		}

		return forwardItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Backward} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BackwardItemProvider backwardItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Backward}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createBackwardAdapter() {
		if (backwardItemProvider == null) {
			backwardItemProvider = new BackwardItemProvider(this);
		}

		return backwardItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Turn} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TurnItemProvider turnItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Turn}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createTurnAdapter() {
		if (turnItemProvider == null) {
			turnItemProvider = new TurnItemProvider(this);
		}

		return turnItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.GapAcceptance} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GapAcceptanceItemProvider gapAcceptanceItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.GapAcceptance}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createGapAcceptanceAdapter() {
		if (gapAcceptanceItemProvider == null) {
			gapAcceptanceItemProvider = new GapAcceptanceItemProvider(this);
		}

		return gapAcceptanceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Action} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActionItemProvider actionItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Action}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createActionAdapter() {
		if (actionItemProvider == null) {
			actionItemProvider = new ActionItemProvider(this);
		}

		return actionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Platoon} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PlatoonItemProvider platoonItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Platoon}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPlatoonAdapter() {
		if (platoonItemProvider == null) {
			platoonItemProvider = new PlatoonItemProvider(this);
		}

		return platoonItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Normal_Vehicle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Normal_VehicleItemProvider normal_VehicleItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Normal_Vehicle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createNormal_VehicleAdapter() {
		if (normal_VehicleItemProvider == null) {
			normal_VehicleItemProvider = new Normal_VehicleItemProvider(this);
		}

		return normal_VehicleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Leading_Vehicle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Leading_VehicleItemProvider leading_VehicleItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Leading_Vehicle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLeading_VehicleAdapter() {
		if (leading_VehicleItemProvider == null) {
			leading_VehicleItemProvider = new Leading_VehicleItemProvider(this);
		}

		return leading_VehicleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Following_Vehicle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Following_VehicleItemProvider following_VehicleItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Following_Vehicle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createFollowing_VehicleAdapter() {
		if (following_VehicleItemProvider == null) {
			following_VehicleItemProvider = new Following_VehicleItemProvider(this);
		}

		return following_VehicleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.PossibleVehicle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PossibleVehicleItemProvider possibleVehicleItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.PossibleVehicle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPossibleVehicleAdapter() {
		if (possibleVehicleItemProvider == null) {
			possibleVehicleItemProvider = new PossibleVehicleItemProvider(this);
		}

		return possibleVehicleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Environment_Condition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Environment_ConditionItemProvider environment_ConditionItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Environment_Condition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createEnvironment_ConditionAdapter() {
		if (environment_ConditionItemProvider == null) {
			environment_ConditionItemProvider = new Environment_ConditionItemProvider(this);
		}

		return environment_ConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Lane_Type} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Lane_TypeItemProvider lane_TypeItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Lane_Type}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLane_TypeAdapter() {
		if (lane_TypeItemProvider == null) {
			lane_TypeItemProvider = new Lane_TypeItemProvider(this);
		}

		return lane_TypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Regulation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RegulationItemProvider regulationItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Regulation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createRegulationAdapter() {
		if (regulationItemProvider == null) {
			regulationItemProvider = new RegulationItemProvider(this);
		}

		return regulationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Safety_Requirement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Safety_RequirementItemProvider safety_RequirementItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Safety_Requirement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSafety_RequirementAdapter() {
		if (safety_RequirementItemProvider == null) {
			safety_RequirementItemProvider = new Safety_RequirementItemProvider(this);
		}

		return safety_RequirementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Weather} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WeatherItemProvider weatherItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Weather}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createWeatherAdapter() {
		if (weatherItemProvider == null) {
			weatherItemProvider = new WeatherItemProvider(this);
		}

		return weatherItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Traffic_Situation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Traffic_SituationItemProvider traffic_SituationItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Traffic_Situation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createTraffic_SituationAdapter() {
		if (traffic_SituationItemProvider == null) {
			traffic_SituationItemProvider = new Traffic_SituationItemProvider(this);
		}

		return traffic_SituationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Special_Condition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Special_ConditionItemProvider special_ConditionItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Special_Condition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSpecial_ConditionAdapter() {
		if (special_ConditionItemProvider == null) {
			special_ConditionItemProvider = new Special_ConditionItemProvider(this);
		}

		return special_ConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Collision} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CollisionItemProvider collisionItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Collision}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCollisionAdapter() {
		if (collisionItemProvider == null) {
			collisionItemProvider = new CollisionItemProvider(this);
		}

		return collisionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Intersection} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IntersectionItemProvider intersectionItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Intersection}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createIntersectionAdapter() {
		if (intersectionItemProvider == null) {
			intersectionItemProvider = new IntersectionItemProvider(this);
		}

		return intersectionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Obstruction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObstructionItemProvider obstructionItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Obstruction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createObstructionAdapter() {
		if (obstructionItemProvider == null) {
			obstructionItemProvider = new ObstructionItemProvider(this);
		}

		return obstructionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Traffic_Light} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Traffic_LightItemProvider traffic_LightItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Traffic_Light}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createTraffic_LightAdapter() {
		if (traffic_LightItemProvider == null) {
			traffic_LightItemProvider = new Traffic_LightItemProvider(this);
		}

		return traffic_LightItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.ExceptionCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExceptionConditionItemProvider exceptionConditionItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.ExceptionCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createExceptionConditionAdapter() {
		if (exceptionConditionItemProvider == null) {
			exceptionConditionItemProvider = new ExceptionConditionItemProvider(this);
		}

		return exceptionConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_Driver_Environment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_Driver_EnvironmentItemProvider link_Driver_EnvironmentItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_Driver_Environment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_Driver_EnvironmentAdapter() {
		if (link_Driver_EnvironmentItemProvider == null) {
			link_Driver_EnvironmentItemProvider = new Link_Driver_EnvironmentItemProvider(this);
		}

		return link_Driver_EnvironmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_Driver_Vehicle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_Driver_VehicleItemProvider link_Driver_VehicleItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_Driver_Vehicle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_Driver_VehicleAdapter() {
		if (link_Driver_VehicleItemProvider == null) {
			link_Driver_VehicleItemProvider = new Link_Driver_VehicleItemProvider(this);
		}

		return link_Driver_VehicleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_Vehicle_Environment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_Vehicle_EnvironmentItemProvider link_Vehicle_EnvironmentItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_Vehicle_Environment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_Vehicle_EnvironmentAdapter() {
		if (link_Vehicle_EnvironmentItemProvider == null) {
			link_Vehicle_EnvironmentItemProvider = new Link_Vehicle_EnvironmentItemProvider(this);
		}

		return link_Vehicle_EnvironmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_DriverProfile_DriverPreference} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_DriverProfile_DriverPreferenceItemProvider link_DriverProfile_DriverPreferenceItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_DriverProfile_DriverPreference}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_DriverProfile_DriverPreferenceAdapter() {
		if (link_DriverProfile_DriverPreferenceItemProvider == null) {
			link_DriverProfile_DriverPreferenceItemProvider = new Link_DriverProfile_DriverPreferenceItemProvider(this);
		}

		return link_DriverProfile_DriverPreferenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_VehicleConfiguration_VehicleType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_VehicleConfiguration_VehicleTypeItemProvider link_VehicleConfiguration_VehicleTypeItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_VehicleConfiguration_VehicleType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_VehicleConfiguration_VehicleTypeAdapter() {
		if (link_VehicleConfiguration_VehicleTypeItemProvider == null) {
			link_VehicleConfiguration_VehicleTypeItemProvider = new Link_VehicleConfiguration_VehicleTypeItemProvider(this);
		}

		return link_VehicleConfiguration_VehicleTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_EnvironmentBackground_PossibleVehicle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_EnvironmentBackground_PossibleVehicleItemProvider link_EnvironmentBackground_PossibleVehicleItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_EnvironmentBackground_PossibleVehicle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_EnvironmentBackground_PossibleVehicleAdapter() {
		if (link_EnvironmentBackground_PossibleVehicleItemProvider == null) {
			link_EnvironmentBackground_PossibleVehicleItemProvider = new Link_EnvironmentBackground_PossibleVehicleItemProvider(this);
		}

		return link_EnvironmentBackground_PossibleVehicleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_EnvironmentBackground_EnvironmentCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_EnvironmentBackground_EnvironmentConditionItemProvider link_EnvironmentBackground_EnvironmentConditionItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_EnvironmentBackground_EnvironmentCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_EnvironmentBackground_EnvironmentConditionAdapter() {
		if (link_EnvironmentBackground_EnvironmentConditionItemProvider == null) {
			link_EnvironmentBackground_EnvironmentConditionItemProvider = new Link_EnvironmentBackground_EnvironmentConditionItemProvider(this);
		}

		return link_EnvironmentBackground_EnvironmentConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_DriverPreference_DriverEmotion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_DriverPreference_DriverEmotionItemProvider link_DriverPreference_DriverEmotionItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_DriverPreference_DriverEmotion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_DriverPreference_DriverEmotionAdapter() {
		if (link_DriverPreference_DriverEmotionItemProvider == null) {
			link_DriverPreference_DriverEmotionItemProvider = new Link_DriverPreference_DriverEmotionItemProvider(this);
		}

		return link_DriverPreference_DriverEmotionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_DriverPreference_DrivingBehaviour} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_DriverPreference_DrivingBehaviourItemProvider link_DriverPreference_DrivingBehaviourItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_DriverPreference_DrivingBehaviour}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_DriverPreference_DrivingBehaviourAdapter() {
		if (link_DriverPreference_DrivingBehaviourItemProvider == null) {
			link_DriverPreference_DrivingBehaviourItemProvider = new Link_DriverPreference_DrivingBehaviourItemProvider(this);
		}

		return link_DriverPreference_DrivingBehaviourItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_DriverPreference_EnvironmentCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_DriverPreference_EnvironmentConditionItemProvider link_DriverPreference_EnvironmentConditionItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_DriverPreference_EnvironmentCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_DriverPreference_EnvironmentConditionAdapter() {
		if (link_DriverPreference_EnvironmentConditionItemProvider == null) {
			link_DriverPreference_EnvironmentConditionItemProvider = new Link_DriverPreference_EnvironmentConditionItemProvider(this);
		}

		return link_DriverPreference_EnvironmentConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_DrivingBehaviour_NormalBehaviour} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_DrivingBehaviour_NormalBehaviourItemProvider link_DrivingBehaviour_NormalBehaviourItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_DrivingBehaviour_NormalBehaviour}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_DrivingBehaviour_NormalBehaviourAdapter() {
		if (link_DrivingBehaviour_NormalBehaviourItemProvider == null) {
			link_DrivingBehaviour_NormalBehaviourItemProvider = new Link_DrivingBehaviour_NormalBehaviourItemProvider(this);
		}

		return link_DrivingBehaviour_NormalBehaviourItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_NormalBehaviour_Following} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_NormalBehaviour_FollowingItemProvider link_NormalBehaviour_FollowingItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_NormalBehaviour_Following}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_NormalBehaviour_FollowingAdapter() {
		if (link_NormalBehaviour_FollowingItemProvider == null) {
			link_NormalBehaviour_FollowingItemProvider = new Link_NormalBehaviour_FollowingItemProvider(this);
		}

		return link_NormalBehaviour_FollowingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_NormalBehaviour_LaneChanging} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_NormalBehaviour_LaneChangingItemProvider link_NormalBehaviour_LaneChangingItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_NormalBehaviour_LaneChanging}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_NormalBehaviour_LaneChangingAdapter() {
		if (link_NormalBehaviour_LaneChangingItemProvider == null) {
			link_NormalBehaviour_LaneChangingItemProvider = new Link_NormalBehaviour_LaneChangingItemProvider(this);
		}

		return link_NormalBehaviour_LaneChangingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_Following_MinGap} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_Following_MinGapItemProvider link_Following_MinGapItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_Following_MinGap}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_Following_MinGapAdapter() {
		if (link_Following_MinGapItemProvider == null) {
			link_Following_MinGapItemProvider = new Link_Following_MinGapItemProvider(this);
		}

		return link_Following_MinGapItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_Following_Forward} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_Following_ForwardItemProvider link_Following_ForwardItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_Following_Forward}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_Following_ForwardAdapter() {
		if (link_Following_ForwardItemProvider == null) {
			link_Following_ForwardItemProvider = new Link_Following_ForwardItemProvider(this);
		}

		return link_Following_ForwardItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_Following_Backward} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_Following_BackwardItemProvider link_Following_BackwardItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_Following_Backward}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_Following_BackwardAdapter() {
		if (link_Following_BackwardItemProvider == null) {
			link_Following_BackwardItemProvider = new Link_Following_BackwardItemProvider(this);
		}

		return link_Following_BackwardItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_LaneChanging_Turn} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_LaneChanging_TurnItemProvider link_LaneChanging_TurnItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_LaneChanging_Turn}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_LaneChanging_TurnAdapter() {
		if (link_LaneChanging_TurnItemProvider == null) {
			link_LaneChanging_TurnItemProvider = new Link_LaneChanging_TurnItemProvider(this);
		}

		return link_LaneChanging_TurnItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_LaneChanging_GapAcceptance} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_LaneChanging_GapAcceptanceItemProvider link_LaneChanging_GapAcceptanceItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_LaneChanging_GapAcceptance}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_LaneChanging_GapAcceptanceAdapter() {
		if (link_LaneChanging_GapAcceptanceItemProvider == null) {
			link_LaneChanging_GapAcceptanceItemProvider = new Link_LaneChanging_GapAcceptanceItemProvider(this);
		}

		return link_LaneChanging_GapAcceptanceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_LaneChanging_EnvironmentCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_LaneChanging_EnvironmentConditionItemProvider link_LaneChanging_EnvironmentConditionItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_LaneChanging_EnvironmentCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_LaneChanging_EnvironmentConditionAdapter() {
		if (link_LaneChanging_EnvironmentConditionItemProvider == null) {
			link_LaneChanging_EnvironmentConditionItemProvider = new Link_LaneChanging_EnvironmentConditionItemProvider(this);
		}

		return link_LaneChanging_EnvironmentConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_AbnormalBehaviour_Action} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_AbnormalBehaviour_ActionItemProvider link_AbnormalBehaviour_ActionItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_AbnormalBehaviour_Action}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_AbnormalBehaviour_ActionAdapter() {
		if (link_AbnormalBehaviour_ActionItemProvider == null) {
			link_AbnormalBehaviour_ActionItemProvider = new Link_AbnormalBehaviour_ActionItemProvider(this);
		}

		return link_AbnormalBehaviour_ActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_Platoon_LeadingVehicle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_Platoon_LeadingVehicleItemProvider link_Platoon_LeadingVehicleItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_Platoon_LeadingVehicle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_Platoon_LeadingVehicleAdapter() {
		if (link_Platoon_LeadingVehicleItemProvider == null) {
			link_Platoon_LeadingVehicleItemProvider = new Link_Platoon_LeadingVehicleItemProvider(this);
		}

		return link_Platoon_LeadingVehicleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_Platoon_FollowingVehicle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_Platoon_FollowingVehicleItemProvider link_Platoon_FollowingVehicleItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_Platoon_FollowingVehicle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_Platoon_FollowingVehicleAdapter() {
		if (link_Platoon_FollowingVehicleItemProvider == null) {
			link_Platoon_FollowingVehicleItemProvider = new Link_Platoon_FollowingVehicleItemProvider(this);
		}

		return link_Platoon_FollowingVehicleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_NormalVehicle_SafetyRequirements} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_NormalVehicle_SafetyRequirementsItemProvider link_NormalVehicle_SafetyRequirementsItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_NormalVehicle_SafetyRequirements}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_NormalVehicle_SafetyRequirementsAdapter() {
		if (link_NormalVehicle_SafetyRequirementsItemProvider == null) {
			link_NormalVehicle_SafetyRequirementsItemProvider = new Link_NormalVehicle_SafetyRequirementsItemProvider(this);
		}

		return link_NormalVehicle_SafetyRequirementsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_FollowingVehicle_FrontVehicle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_FollowingVehicle_FrontVehicleItemProvider link_FollowingVehicle_FrontVehicleItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_FollowingVehicle_FrontVehicle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_FollowingVehicle_FrontVehicleAdapter() {
		if (link_FollowingVehicle_FrontVehicleItemProvider == null) {
			link_FollowingVehicle_FrontVehicleItemProvider = new Link_FollowingVehicle_FrontVehicleItemProvider(this);
		}

		return link_FollowingVehicle_FrontVehicleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_EnvironmentCondition_LaneType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_EnvironmentCondition_LaneTypeItemProvider link_EnvironmentCondition_LaneTypeItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_EnvironmentCondition_LaneType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_EnvironmentCondition_LaneTypeAdapter() {
		if (link_EnvironmentCondition_LaneTypeItemProvider == null) {
			link_EnvironmentCondition_LaneTypeItemProvider = new Link_EnvironmentCondition_LaneTypeItemProvider(this);
		}

		return link_EnvironmentCondition_LaneTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_EnvironmentCondition_Regulations} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_EnvironmentCondition_RegulationsItemProvider link_EnvironmentCondition_RegulationsItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_EnvironmentCondition_Regulations}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_EnvironmentCondition_RegulationsAdapter() {
		if (link_EnvironmentCondition_RegulationsItemProvider == null) {
			link_EnvironmentCondition_RegulationsItemProvider = new Link_EnvironmentCondition_RegulationsItemProvider(this);
		}

		return link_EnvironmentCondition_RegulationsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_EnvironmentCondition_Weather} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_EnvironmentCondition_WeatherItemProvider link_EnvironmentCondition_WeatherItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_EnvironmentCondition_Weather}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_EnvironmentCondition_WeatherAdapter() {
		if (link_EnvironmentCondition_WeatherItemProvider == null) {
			link_EnvironmentCondition_WeatherItemProvider = new Link_EnvironmentCondition_WeatherItemProvider(this);
		}

		return link_EnvironmentCondition_WeatherItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_EnvironmentCondition_TrafficCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_EnvironmentCondition_TrafficConditionItemProvider link_EnvironmentCondition_TrafficConditionItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_EnvironmentCondition_TrafficCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_EnvironmentCondition_TrafficConditionAdapter() {
		if (link_EnvironmentCondition_TrafficConditionItemProvider == null) {
			link_EnvironmentCondition_TrafficConditionItemProvider = new Link_EnvironmentCondition_TrafficConditionItemProvider(this);
		}

		return link_EnvironmentCondition_TrafficConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_EnvironmentCondition_SpecialCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_EnvironmentCondition_SpecialConditionItemProvider link_EnvironmentCondition_SpecialConditionItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_EnvironmentCondition_SpecialCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_EnvironmentCondition_SpecialConditionAdapter() {
		if (link_EnvironmentCondition_SpecialConditionItemProvider == null) {
			link_EnvironmentCondition_SpecialConditionItemProvider = new Link_EnvironmentCondition_SpecialConditionItemProvider(this);
		}

		return link_EnvironmentCondition_SpecialConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_LaneType_Regulation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_LaneType_RegulationItemProvider link_LaneType_RegulationItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_LaneType_Regulation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_LaneType_RegulationAdapter() {
		if (link_LaneType_RegulationItemProvider == null) {
			link_LaneType_RegulationItemProvider = new Link_LaneType_RegulationItemProvider(this);
		}

		return link_LaneType_RegulationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_SafetyRequirement_Regulation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_SafetyRequirement_RegulationItemProvider link_SafetyRequirement_RegulationItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_SafetyRequirement_Regulation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_SafetyRequirement_RegulationAdapter() {
		if (link_SafetyRequirement_RegulationItemProvider == null) {
			link_SafetyRequirement_RegulationItemProvider = new Link_SafetyRequirement_RegulationItemProvider(this);
		}

		return link_SafetyRequirement_RegulationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_SpecialCondition_Intersection} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_SpecialCondition_IntersectionItemProvider link_SpecialCondition_IntersectionItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_SpecialCondition_Intersection}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_SpecialCondition_IntersectionAdapter() {
		if (link_SpecialCondition_IntersectionItemProvider == null) {
			link_SpecialCondition_IntersectionItemProvider = new Link_SpecialCondition_IntersectionItemProvider(this);
		}

		return link_SpecialCondition_IntersectionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_Collision_Obstruction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_Collision_ObstructionItemProvider link_Collision_ObstructionItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_Collision_Obstruction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_Collision_ObstructionAdapter() {
		if (link_Collision_ObstructionItemProvider == null) {
			link_Collision_ObstructionItemProvider = new Link_Collision_ObstructionItemProvider(this);
		}

		return link_Collision_ObstructionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_Intersection_TrafficLight} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_Intersection_TrafficLightItemProvider link_Intersection_TrafficLightItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_Intersection_TrafficLight}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_Intersection_TrafficLightAdapter() {
		if (link_Intersection_TrafficLightItemProvider == null) {
			link_Intersection_TrafficLightItemProvider = new Link_Intersection_TrafficLightItemProvider(this);
		}

		return link_Intersection_TrafficLightItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.RoadSegment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RoadSegmentItemProvider roadSegmentItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.RoadSegment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createRoadSegmentAdapter() {
		if (roadSegmentItemProvider == null) {
			roadSegmentItemProvider = new RoadSegmentItemProvider(this);
		}

		return roadSegmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.SmartSensor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SmartSensorItemProvider smartSensorItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.SmartSensor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSmartSensorAdapter() {
		if (smartSensorItemProvider == null) {
			smartSensorItemProvider = new SmartSensorItemProvider(this);
		}

		return smartSensorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Road_Side_Unit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Road_Side_UnitItemProvider road_Side_UnitItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Road_Side_Unit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createRoad_Side_UnitAdapter() {
		if (road_Side_UnitItemProvider == null) {
			road_Side_UnitItemProvider = new Road_Side_UnitItemProvider(this);
		}

		return road_Side_UnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.ChargingStation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChargingStationItemProvider chargingStationItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.ChargingStation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createChargingStationAdapter() {
		if (chargingStationItemProvider == null) {
			chargingStationItemProvider = new ChargingStationItemProvider(this);
		}

		return chargingStationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.CommunicationInterface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CommunicationInterfaceItemProvider communicationInterfaceItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.CommunicationInterface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCommunicationInterfaceAdapter() {
		if (communicationInterfaceItemProvider == null) {
			communicationInterfaceItemProvider = new CommunicationInterfaceItemProvider(this);
		}

		return communicationInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.CooperativeBehavior} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CooperativeBehaviorItemProvider cooperativeBehaviorItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.CooperativeBehavior}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCooperativeBehaviorAdapter() {
		if (cooperativeBehaviorItemProvider == null) {
			cooperativeBehaviorItemProvider = new CooperativeBehaviorItemProvider(this);
		}

		return cooperativeBehaviorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Goal} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GoalItemProvider goalItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Goal}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createGoalAdapter() {
		if (goalItemProvider == null) {
			goalItemProvider = new GoalItemProvider(this);
		}

		return goalItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_Infrastructure_VehicleConfiguration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_Infrastructure_VehicleConfigurationItemProvider link_Infrastructure_VehicleConfigurationItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_Infrastructure_VehicleConfiguration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_Infrastructure_VehicleConfigurationAdapter() {
		if (link_Infrastructure_VehicleConfigurationItemProvider == null) {
			link_Infrastructure_VehicleConfigurationItemProvider = new Link_Infrastructure_VehicleConfigurationItemProvider(this);
		}

		return link_Infrastructure_VehicleConfigurationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_CommunicationInterface_VehicleConfiguration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_CommunicationInterface_VehicleConfigurationItemProvider link_CommunicationInterface_VehicleConfigurationItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_CommunicationInterface_VehicleConfiguration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_CommunicationInterface_VehicleConfigurationAdapter() {
		if (link_CommunicationInterface_VehicleConfigurationItemProvider == null) {
			link_CommunicationInterface_VehicleConfigurationItemProvider = new Link_CommunicationInterface_VehicleConfigurationItemProvider(this);
		}

		return link_CommunicationInterface_VehicleConfigurationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_Goal_DrivingBehaviour} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_Goal_DrivingBehaviourItemProvider link_Goal_DrivingBehaviourItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_Goal_DrivingBehaviour}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_Goal_DrivingBehaviourAdapter() {
		if (link_Goal_DrivingBehaviourItemProvider == null) {
			link_Goal_DrivingBehaviourItemProvider = new Link_Goal_DrivingBehaviourItemProvider(this);
		}

		return link_Goal_DrivingBehaviourItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_CooperativeBehaviour_CommunicationInterface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_CooperativeBehaviour_CommunicationInterfaceItemProvider link_CooperativeBehaviour_CommunicationInterfaceItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_CooperativeBehaviour_CommunicationInterface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_CooperativeBehaviour_CommunicationInterfaceAdapter() {
		if (link_CooperativeBehaviour_CommunicationInterfaceItemProvider == null) {
			link_CooperativeBehaviour_CommunicationInterfaceItemProvider = new Link_CooperativeBehaviour_CommunicationInterfaceItemProvider(this);
		}

		return link_CooperativeBehaviour_CommunicationInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_CommunicationInterface_Infrastructure} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_CommunicationInterface_InfrastructureItemProvider link_CommunicationInterface_InfrastructureItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_CommunicationInterface_Infrastructure}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_CommunicationInterface_InfrastructureAdapter() {
		if (link_CommunicationInterface_InfrastructureItemProvider == null) {
			link_CommunicationInterface_InfrastructureItemProvider = new Link_CommunicationInterface_InfrastructureItemProvider(this);
		}

		return link_CommunicationInterface_InfrastructureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_CooperativeBehaviour_VehicleConfiguration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_CooperativeBehaviour_VehicleConfigurationItemProvider link_CooperativeBehaviour_VehicleConfigurationItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_CooperativeBehaviour_VehicleConfiguration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_CooperativeBehaviour_VehicleConfigurationAdapter() {
		if (link_CooperativeBehaviour_VehicleConfigurationItemProvider == null) {
			link_CooperativeBehaviour_VehicleConfigurationItemProvider = new Link_CooperativeBehaviour_VehicleConfigurationItemProvider(this);
		}

		return link_CooperativeBehaviour_VehicleConfigurationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_TrafficSituation_EnvironmentCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_TrafficSituation_EnvironmentConditionItemProvider link_TrafficSituation_EnvironmentConditionItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_TrafficSituation_EnvironmentCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_TrafficSituation_EnvironmentConditionAdapter() {
		if (link_TrafficSituation_EnvironmentConditionItemProvider == null) {
			link_TrafficSituation_EnvironmentConditionItemProvider = new Link_TrafficSituation_EnvironmentConditionItemProvider(this);
		}

		return link_TrafficSituation_EnvironmentConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_Following_LaneChanging} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_Following_LaneChangingItemProvider link_Following_LaneChangingItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_Following_LaneChanging}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_Following_LaneChangingAdapter() {
		if (link_Following_LaneChangingItemProvider == null) {
			link_Following_LaneChangingItemProvider = new Link_Following_LaneChangingItemProvider(this);
		}

		return link_Following_LaneChangingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_Collision_SpecialCondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_Collision_SpecialConditionItemProvider link_Collision_SpecialConditionItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_Collision_SpecialCondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_Collision_SpecialConditionAdapter() {
		if (link_Collision_SpecialConditionItemProvider == null) {
			link_Collision_SpecialConditionItemProvider = new Link_Collision_SpecialConditionItemProvider(this);
		}

		return link_Collision_SpecialConditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_Action_Backward} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_Action_BackwardItemProvider link_Action_BackwardItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_Action_Backward}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_Action_BackwardAdapter() {
		if (link_Action_BackwardItemProvider == null) {
			link_Action_BackwardItemProvider = new Link_Action_BackwardItemProvider(this);
		}

		return link_Action_BackwardItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_Action_Forward} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_Action_ForwardItemProvider link_Action_ForwardItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_Action_Forward}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_Action_ForwardAdapter() {
		if (link_Action_ForwardItemProvider == null) {
			link_Action_ForwardItemProvider = new Link_Action_ForwardItemProvider(this);
		}

		return link_Action_ForwardItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_Action_Turn} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_Action_TurnItemProvider link_Action_TurnItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_Action_Turn}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_Action_TurnAdapter() {
		if (link_Action_TurnItemProvider == null) {
			link_Action_TurnItemProvider = new Link_Action_TurnItemProvider(this);
		}

		return link_Action_TurnItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link intelligentMobility.Link_KnowledgeAndSkill_DriverPreference} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Link_KnowledgeAndSkill_DriverPreferenceItemProvider link_KnowledgeAndSkill_DriverPreferenceItemProvider;

	/**
	 * This creates an adapter for a {@link intelligentMobility.Link_KnowledgeAndSkill_DriverPreference}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLink_KnowledgeAndSkill_DriverPreferenceAdapter() {
		if (link_KnowledgeAndSkill_DriverPreferenceItemProvider == null) {
			link_KnowledgeAndSkill_DriverPreferenceItemProvider = new Link_KnowledgeAndSkill_DriverPreferenceItemProvider(this);
		}

		return link_KnowledgeAndSkill_DriverPreferenceItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class) || (((Class)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (mobilitySystemItemProvider != null) mobilitySystemItemProvider.dispose();
		if (driver_ProfileItemProvider != null) driver_ProfileItemProvider.dispose();
		if (vehicle_ConfigurationItemProvider != null) vehicle_ConfigurationItemProvider.dispose();
		if (environment_BackgroundItemProvider != null) environment_BackgroundItemProvider.dispose();
		if (driver_PreferenceItemProvider != null) driver_PreferenceItemProvider.dispose();
		if (knowledge_and_SkillItemProvider != null) knowledge_and_SkillItemProvider.dispose();
		if (driver_EmotionItemProvider != null) driver_EmotionItemProvider.dispose();
		if (driving_BehaviourItemProvider != null) driving_BehaviourItemProvider.dispose();
		if (normal_BehaviourItemProvider != null) normal_BehaviourItemProvider.dispose();
		if (followingItemProvider != null) followingItemProvider.dispose();
		if (laneChangingItemProvider != null) laneChangingItemProvider.dispose();
		if (abnormal_BehaviourItemProvider != null) abnormal_BehaviourItemProvider.dispose();
		if (forwardItemProvider != null) forwardItemProvider.dispose();
		if (backwardItemProvider != null) backwardItemProvider.dispose();
		if (turnItemProvider != null) turnItemProvider.dispose();
		if (gapAcceptanceItemProvider != null) gapAcceptanceItemProvider.dispose();
		if (actionItemProvider != null) actionItemProvider.dispose();
		if (platoonItemProvider != null) platoonItemProvider.dispose();
		if (normal_VehicleItemProvider != null) normal_VehicleItemProvider.dispose();
		if (leading_VehicleItemProvider != null) leading_VehicleItemProvider.dispose();
		if (following_VehicleItemProvider != null) following_VehicleItemProvider.dispose();
		if (possibleVehicleItemProvider != null) possibleVehicleItemProvider.dispose();
		if (environment_ConditionItemProvider != null) environment_ConditionItemProvider.dispose();
		if (lane_TypeItemProvider != null) lane_TypeItemProvider.dispose();
		if (regulationItemProvider != null) regulationItemProvider.dispose();
		if (safety_RequirementItemProvider != null) safety_RequirementItemProvider.dispose();
		if (weatherItemProvider != null) weatherItemProvider.dispose();
		if (traffic_SituationItemProvider != null) traffic_SituationItemProvider.dispose();
		if (special_ConditionItemProvider != null) special_ConditionItemProvider.dispose();
		if (collisionItemProvider != null) collisionItemProvider.dispose();
		if (intersectionItemProvider != null) intersectionItemProvider.dispose();
		if (obstructionItemProvider != null) obstructionItemProvider.dispose();
		if (traffic_LightItemProvider != null) traffic_LightItemProvider.dispose();
		if (exceptionConditionItemProvider != null) exceptionConditionItemProvider.dispose();
		if (link_Driver_EnvironmentItemProvider != null) link_Driver_EnvironmentItemProvider.dispose();
		if (link_Driver_VehicleItemProvider != null) link_Driver_VehicleItemProvider.dispose();
		if (link_Vehicle_EnvironmentItemProvider != null) link_Vehicle_EnvironmentItemProvider.dispose();
		if (link_DriverProfile_DriverPreferenceItemProvider != null) link_DriverProfile_DriverPreferenceItemProvider.dispose();
		if (link_VehicleConfiguration_VehicleTypeItemProvider != null) link_VehicleConfiguration_VehicleTypeItemProvider.dispose();
		if (link_EnvironmentBackground_PossibleVehicleItemProvider != null) link_EnvironmentBackground_PossibleVehicleItemProvider.dispose();
		if (link_EnvironmentBackground_EnvironmentConditionItemProvider != null) link_EnvironmentBackground_EnvironmentConditionItemProvider.dispose();
		if (link_DriverPreference_DriverEmotionItemProvider != null) link_DriverPreference_DriverEmotionItemProvider.dispose();
		if (link_DriverPreference_DrivingBehaviourItemProvider != null) link_DriverPreference_DrivingBehaviourItemProvider.dispose();
		if (link_DriverPreference_EnvironmentConditionItemProvider != null) link_DriverPreference_EnvironmentConditionItemProvider.dispose();
		if (link_DrivingBehaviour_NormalBehaviourItemProvider != null) link_DrivingBehaviour_NormalBehaviourItemProvider.dispose();
		if (link_NormalBehaviour_FollowingItemProvider != null) link_NormalBehaviour_FollowingItemProvider.dispose();
		if (link_NormalBehaviour_LaneChangingItemProvider != null) link_NormalBehaviour_LaneChangingItemProvider.dispose();
		if (link_Following_MinGapItemProvider != null) link_Following_MinGapItemProvider.dispose();
		if (link_Following_ForwardItemProvider != null) link_Following_ForwardItemProvider.dispose();
		if (link_Following_BackwardItemProvider != null) link_Following_BackwardItemProvider.dispose();
		if (link_LaneChanging_TurnItemProvider != null) link_LaneChanging_TurnItemProvider.dispose();
		if (link_LaneChanging_GapAcceptanceItemProvider != null) link_LaneChanging_GapAcceptanceItemProvider.dispose();
		if (link_LaneChanging_EnvironmentConditionItemProvider != null) link_LaneChanging_EnvironmentConditionItemProvider.dispose();
		if (link_AbnormalBehaviour_ActionItemProvider != null) link_AbnormalBehaviour_ActionItemProvider.dispose();
		if (link_Platoon_LeadingVehicleItemProvider != null) link_Platoon_LeadingVehicleItemProvider.dispose();
		if (link_Platoon_FollowingVehicleItemProvider != null) link_Platoon_FollowingVehicleItemProvider.dispose();
		if (link_NormalVehicle_SafetyRequirementsItemProvider != null) link_NormalVehicle_SafetyRequirementsItemProvider.dispose();
		if (link_FollowingVehicle_FrontVehicleItemProvider != null) link_FollowingVehicle_FrontVehicleItemProvider.dispose();
		if (link_EnvironmentCondition_LaneTypeItemProvider != null) link_EnvironmentCondition_LaneTypeItemProvider.dispose();
		if (link_EnvironmentCondition_RegulationsItemProvider != null) link_EnvironmentCondition_RegulationsItemProvider.dispose();
		if (link_EnvironmentCondition_WeatherItemProvider != null) link_EnvironmentCondition_WeatherItemProvider.dispose();
		if (link_EnvironmentCondition_TrafficConditionItemProvider != null) link_EnvironmentCondition_TrafficConditionItemProvider.dispose();
		if (link_EnvironmentCondition_SpecialConditionItemProvider != null) link_EnvironmentCondition_SpecialConditionItemProvider.dispose();
		if (link_LaneType_RegulationItemProvider != null) link_LaneType_RegulationItemProvider.dispose();
		if (link_SafetyRequirement_RegulationItemProvider != null) link_SafetyRequirement_RegulationItemProvider.dispose();
		if (link_SpecialCondition_IntersectionItemProvider != null) link_SpecialCondition_IntersectionItemProvider.dispose();
		if (link_Collision_ObstructionItemProvider != null) link_Collision_ObstructionItemProvider.dispose();
		if (link_Intersection_TrafficLightItemProvider != null) link_Intersection_TrafficLightItemProvider.dispose();
		if (roadSegmentItemProvider != null) roadSegmentItemProvider.dispose();
		if (smartSensorItemProvider != null) smartSensorItemProvider.dispose();
		if (road_Side_UnitItemProvider != null) road_Side_UnitItemProvider.dispose();
		if (chargingStationItemProvider != null) chargingStationItemProvider.dispose();
		if (communicationInterfaceItemProvider != null) communicationInterfaceItemProvider.dispose();
		if (cooperativeBehaviorItemProvider != null) cooperativeBehaviorItemProvider.dispose();
		if (goalItemProvider != null) goalItemProvider.dispose();
		if (link_Infrastructure_VehicleConfigurationItemProvider != null) link_Infrastructure_VehicleConfigurationItemProvider.dispose();
		if (link_CommunicationInterface_VehicleConfigurationItemProvider != null) link_CommunicationInterface_VehicleConfigurationItemProvider.dispose();
		if (link_Goal_DrivingBehaviourItemProvider != null) link_Goal_DrivingBehaviourItemProvider.dispose();
		if (link_CooperativeBehaviour_CommunicationInterfaceItemProvider != null) link_CooperativeBehaviour_CommunicationInterfaceItemProvider.dispose();
		if (link_CommunicationInterface_InfrastructureItemProvider != null) link_CommunicationInterface_InfrastructureItemProvider.dispose();
		if (link_CooperativeBehaviour_VehicleConfigurationItemProvider != null) link_CooperativeBehaviour_VehicleConfigurationItemProvider.dispose();
		if (link_TrafficSituation_EnvironmentConditionItemProvider != null) link_TrafficSituation_EnvironmentConditionItemProvider.dispose();
		if (link_Following_LaneChangingItemProvider != null) link_Following_LaneChangingItemProvider.dispose();
		if (link_Collision_SpecialConditionItemProvider != null) link_Collision_SpecialConditionItemProvider.dispose();
		if (link_Action_BackwardItemProvider != null) link_Action_BackwardItemProvider.dispose();
		if (link_Action_ForwardItemProvider != null) link_Action_ForwardItemProvider.dispose();
		if (link_Action_TurnItemProvider != null) link_Action_TurnItemProvider.dispose();
		if (link_KnowledgeAndSkill_DriverPreferenceItemProvider != null) link_KnowledgeAndSkill_DriverPreferenceItemProvider.dispose();
	}

}
