pluginName=DrivingBehaviourMetamodel Plugin
providerName=Sample Plugin Provider, Inc

editorName=DrivingBehaviourMetamodel Diagram Editing
context.description=DrivingBehaviourMetamodel Diagram Editing
context.name=In DrivingBehaviourMetamodel Diagram Editor
newWizardName=DrivingBehaviourMetamodel Diagram
newWizardDesc=Creates DrivingBehaviourMetamodel diagram.

initDiagramActionLabel=Initialize drivingbehaviourmetamodel_diagram diagram file


navigatorContentName=*.drivingbehaviourmetamodel_diagram diagram contents
domainNavigatorContentName=*.drivingbehaviourmetamodel model contents
update.diagram.name=Update DrivingBehaviourMetamodel diagram
update.diagram.description=Perform DrivingBehaviourMetamodel diagram update


# Property Sheet
tab.appearance=Appearance
tab.diagram=Rulers & Grid
tab.domain=Core

# Preferences
prefpage.DMB_ExtendedMetamodel.diagram.general=DrivingBehaviourMetamodel Diagram
prefpage.DMB_ExtendedMetamodel.diagram.appearance=Appearance
prefpage.DMB_ExtendedMetamodel.diagram.connections=Connections
prefpage.DMB_ExtendedMetamodel.diagram.printing=Printing
prefpage.DMB_ExtendedMetamodel.diagram.rulersAndGrid=Rulers And Grid


# Providers
metatype.name.Model_1000=Undefined
metatype.name.Special_Condition_2001=Special_Condition
metatype.name.Weather_2002=Weather
metatype.name.Traffic_Light_2003=Traffic_Light
metatype.name.Knowledge_and_Skill_2004=Knowledge_and_Skill
metatype.name.Obstruction_2005=Obstruction
metatype.name.Driver_Preference_2006=Driver_Preference
metatype.name.Intersection_2007=Intersection
metatype.name.Vehicle_Configuration_2008=Vehicle_Configuration
metatype.name.Environment_Condition_2009=Environment_Condition
metatype.name.Platoon_2010=Platoon
metatype.name.Forward_2011=Forward
metatype.name.Lane_Type_2012=Lane_Type
metatype.name.Environment_Background_2013=Environment_Background
metatype.name.Turn_2014=Turn
metatype.name.LaneChanging_2015=LaneChanging
metatype.name.Driver_Emotion_2016=Driver_Emotion
metatype.name.Collision_2017=Collision
metatype.name.PossibleVehicle_2018=PossibleVehicle
metatype.name.Following_2019=Following
metatype.name.GapAcceptance_2020=GapAcceptance
metatype.name.Leading_Vehicle_2021=Leading_Vehicle
metatype.name.Backward_2022=Backward
metatype.name.Regulation_2023=Regulation
metatype.name.Traffic_Situation_2024=Traffic_Situation
metatype.name.Driver_Profile_2025=Driver_Profile
metatype.name.Safety_Requirement_2026=Safety_Requirement
metatype.name.Driving_Behaviour_2027=Driving_Behaviour
metatype.name.Following_Vehicle_2028=Following_Vehicle
metatype.name.Abnormal_Behaviour_2029=Abnormal_Behaviour
metatype.name.Link_LaneType_Regulation_4001=Link_LaneType_Regulation
metatype.name.Link_Driver_Vehicle_4002=Link_Driver_Vehicle
metatype.name.Link_EnvironmentBackground_PossibleVehicle_4003=Link_EnvironmentBackground_PossibleVehicle
metatype.name.Link_Vehicle_Environment_4004=Link_Vehicle_Environment
metatype.name.Link_NormalVehicle_SafetyRequirements_4005=Link_NormalVehicle_SafetyRequirements
metatype.name.Link_DriverProfile_DriverPreference_4006=Link_DriverProfile_DriverPreference
metatype.name.Link_Collision_Obstruction_4007=Link_Collision_Obstruction
metatype.name.Link_Platoon_FollowingVehicle_4008=Link_Platoon_FollowingVehicle
metatype.name.Link_DriverPreference_EnvironmentCondition_4009=Link_DriverPreference_EnvironmentCondition
metatype.name.Link_AbnormalBehaviour_Action_4010=Link_AbnormalBehaviour_Action
metatype.name.Link_Following_Forward_4011=Link_Following_Forward
metatype.name.Link_EnvironmentCondition_LaneType_4012=Link_EnvironmentCondition_LaneType
metatype.name.Link_VehicleConfiguration_VehicleType_4013=Link_VehicleConfiguration_VehicleType
metatype.name.Link_Platoon_LeadingVehicle_4014=Link_Platoon_LeadingVehicle
metatype.name.Link_Driver_Environment_4015=Link_Driver_Environment
metatype.name.Link_LaneChanging_Turn_4016=Link_LaneChanging_Turn
metatype.name.Link_EnvironmentCondition_TrafficCondition_4017=Link_EnvironmentCondition_TrafficCondition
metatype.name.Link_Intersection_TrafficLight_4018=Link_Intersection_TrafficLight
metatype.name.Link_Following_MinGap_4019=Link_Following_MinGap
metatype.name.Link_NormalBehaviour_LaneChanging_4020=Link_NormalBehaviour_LaneChanging
metatype.name.Link_SafetyRequirement_Regulation_4021=Link_SafetyRequirement_Regulation
metatype.name.Link_DriverPreference_DrivingBehaviour_4022=Link_DriverPreference_DrivingBehaviour
metatype.name.Link_FollowingVehicle_FrontVehicle_4023=Link_FollowingVehicle_FrontVehicle
metatype.name.Link_DriverPreference_DriverEmotion_4024=Link_DriverPreference_DriverEmotion
metatype.name.Link_EnvironmentBackground_EnvironmentCondition_4025=Link_EnvironmentBackground_EnvironmentCondition
metatype.name.Link_EnvironmentCondition_Weather_4026=Link_EnvironmentCondition_Weather
metatype.name.Link_EnvironmentCondition_SpecialCondition_4027=Link_EnvironmentCondition_SpecialCondition
metatype.name.Link_SpecialCondition_Intersection_4028=Link_SpecialCondition_Intersection
metatype.name.Link_Following_Backward_4029=Link_Following_Backward
metatype.name.Link_EnvironmentCondition_Regulations_4030=Link_EnvironmentCondition_Regulations
metatype.name.Link_DrivingBehaviour_NormalBehaviour_4031=Link_DrivingBehaviour_NormalBehaviour
metatype.name.Link_LaneChanging_EnvironmentCondition_4032=Link_LaneChanging_EnvironmentCondition
metatype.name.Link_LaneChanging_GapAcceptance_4033=Link_LaneChanging_GapAcceptance
metatype.name.Link_NormalBehaviour_Following_4034=Link_NormalBehaviour_Following

# Commands and menu actions
cmdcategory.name=DrivingBehaviourMetamodel Editor Commands
cmdcategory.desc=DrivingBehaviourMetamodel Editor Commands

metatype.name.MobilitySystem_1000=Undefined
metatype.name.Special_Condition_2059=Special_Condition
metatype.name.Weather_2060=Weather
metatype.name.Traffic_Light_2061=Traffic_Light
metatype.name.Knowledge_and_Skill_2062=Knowledge_and_Skill
metatype.name.Obstruction_2063=Obstruction
metatype.name.Driver_Preference_2064=Driver_Preference
metatype.name.Intersection_2065=Intersection
metatype.name.Vehicle_Configuration_2037=Vehicle_Configuration
metatype.name.Environment_Condition_2066=Environment_Condition
metatype.name.Platoon_2067=Platoon
metatype.name.Forward_2068=Forward
metatype.name.Lane_Type_2069=Lane_Type
metatype.name.Environment_Background_2042=Environment_Background
metatype.name.Turn_2070=Turn
metatype.name.LaneChanging_2071=LaneChanging
metatype.name.Driver_Emotion_2072=Driver_Emotion
metatype.name.Collision_2073=Collision
metatype.name.PossibleVehicle_2074=PossibleVehicle
metatype.name.Following_2075=Following
metatype.name.GapAcceptance_2076=GapAcceptance
metatype.name.Leading_Vehicle_2077=Leading_Vehicle
metatype.name.Backward_2078=Backward
metatype.name.Regulation_2079=Regulation
metatype.name.Traffic_Situation_2080=Traffic_Situation
metatype.name.Driver_Profile_2054=Driver_Profile
metatype.name.Safety_Requirement_2081=Safety_Requirement
metatype.name.Driving_Behaviour_2082=Driving_Behaviour
metatype.name.Following_Vehicle_2083=Following_Vehicle
metatype.name.Abnormal_Behaviour_2084=Abnormal_Behaviour
metatype.name.Backward_2030=Backward
metatype.name.Intersection_2031=Intersection
metatype.name.CommunicationInterface_2032=CommunicationInterface
metatype.name.Goal_2033=Goal
metatype.name.Normal_Behaviour_2034=Normal_Behaviour
metatype.name.Platoon_2035=Platoon
metatype.name.Normal_Vehicle_2036=Normal_Vehicle
metatype.name.CooperativeBehavior_2037=CooperativeBehavior
metatype.name.Link_Infrastructure_VehicleConfiguration_4035=Link_Infrastructure_VehicleConfiguration
metatype.name.Link_CommunicationInterface_VehicleConfiguration_4036=Link_CommunicationInterface_VehicleConfiguration
metatype.name.Link_Goal_DrivingBehaviour_4037=Link_Goal_DrivingBehaviour
metatype.name.Link_CooperativeBehaviour_CommunicationInterface_4038=Link_CooperativeBehaviour_CommunicationInterface
metatype.name.Link_CommunicationInterface_Infrastructure_4039=Link_CommunicationInterface_Infrastructure
metatype.name.Link_CooperativeBehaviour_VehicleConfiguration_4040=Link_CooperativeBehaviour_VehicleConfiguration
metatype.name.Turn_2038=Turn
metatype.name.Link_TrafficSituation_EnvironmentCondition_4041=Link_TrafficSituation_EnvironmentCondition
metatype.name.Link_Collision_SpecialCondition_4042=Link_Collision_SpecialCondition
metatype.name.Link_Following_LaneChanging_4043=Link_Following_LaneChanging
metatype.name.Action_2039=Action
metatype.name.Link_Action_Backward_4044=Link_Action_Backward
metatype.name.Link_Action_Forward_4045=Link_Action_Forward
metatype.name.Link_Action_Turn_4046=Link_Action_Turn
metatype.name.Link_KnowledgeAndSkill_DriverPreference_4047=Link_KnowledgeAndSkill_DriverPreference
