from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional


# This module mirrors the PlantUML framework (VM01-extended_twimo_framework.puml)
# and the VM02 EAF architecture diagram (TWIMO_VM02_EAF_Diagram_new.png).
# It defines lightweight design-time components used as a blueprint for the pipeline.


# ------------------------------------------------------------
# Supervision modes  (PNG architecture VM02, left column)
# ------------------------------------------------------------

class SupervisionMode(str, Enum):
    """Data provenance / supervision strategy — three labelling paths in the PNG VM02 architecture.

    Path A — PROXY_HEURISTIC:
        Labels generated by threshold-based heuristic rules.
        Implementation: twimo/data/csv_session.py (proxy label logic)

    Path B — EAF_EXPERT:
        Expert ELAN/EAF annotations (Goal, Stimulus, Cause, Attention tiers).
        Implementation: twimo/strategies_eaf/parse_eaf.py,
                        twimo/strategies_eaf/align_eaf_to_sensors*.py

    Path C — YOLO_DETECTION:
        Offline YOLOv8 object-detection feature extraction, cached as .npy vectors.
        Implementation: twimo/strategies_eaf/two_stage_yolo.py,
                        twimo/strategies_eaf/two_stage_yolo_improved.py
    """
    PROXY_HEURISTIC = "proxy"
    EAF_EXPERT      = "eaf"
    YOLO_DETECTION  = "yolo"


# ------------------------------------------------------------
# Data & Evidence
# ------------------------------------------------------------

@dataclass
class DataSource:
    """Single data stream — one modality, one file path.

    DTE Mapping: model.dataAndEvidence.Dataset → DataSource
    Implementation: twimo/data/csv_loaders.py (individual CSV readers),
                    twimo/data/prealigned.py (.npy prealigned arrays)
    """
    name: str
    modality: str  # 'video' | 'sensors' | 'labels'
    path: str


@dataclass
class Dataset:
    """Collection of data sources for a session bundle.

    DTE Mapping: model.dataAndEvidence.Dataset
    Implementation: twimo/data/csv_session.py,
                    twimo/data/manifest.py (JSONL registry of SessionRecord objects)
    """
    name: str
    sources: List[DataSource] = field(default_factory=list)


# ------------------------------------------------------------
# Digital Shadow  (PNG VM02: "Digital Shadow — Data-Centric" layer)
# ------------------------------------------------------------

@dataclass
class DigitalShadow:
    """The Time-Aligned Shadow — fused feature matrix produced by the Digital Shadow layer.

    Aggregates sensor signals, EAF annotations, and optionally YOLOv8 detection
    features into a single 3 Hz time-aligned array per session.

    DTE Mapping: model.DigitalShadow
    PNG Layer: Digital Shadow (Data-Centric) → Time-Aligned Shadow (Features and Signals)
    Implementation:
        twimo/data/csv_session.py          — sensor ingestion + 3 Hz resampling + proxy labels
        twimo/data/prealigned.py           — loads pre-aligned .npy arrays
        twimo/data/generate_sensor_npy.py  — generates sensor .npy from CSV
        twimo/strategies_eaf/two_stage_yolo.py  — detection features, cached .npy (Supervision C)
    """
    name: str
    dataset: Dataset
    perception: "PerceptionService"
    supervision_mode: SupervisionMode
    sample_hz: float
    n_features: int  # 60+ sensors-only | 33 sensors+yolo-13 | 58 sensors+yolo-39


# ------------------------------------------------------------
# AI-Based Services
# ------------------------------------------------------------

@dataclass
class PerceptionService:
    """Handles multi-modal feature extraction from raw video and sensor data.

    DTE Mapping: model.aiBasedServices.perception.PerceptionService
    PNG Layer: Digital Shadow → EAF Alignment (Tiers→Frames) / YOLOv8 Feature Extraction

    Extractors:
        'torch' — CNN video features via ResNet18 / MobileNetV3
                  Implementation: twimo/video/torch_extractor.py
        'eaf'   — ELAN annotation parser (Tiers → frame-aligned labels, Supervision B)
                  Implementation: twimo/strategies_eaf/align_eaf_to_sensors*.py
        'yolo'  — Offline YOLOv8 object detection (13 base / 39 improved features, Supervision C)
                  Implementation: twimo/strategies_eaf/two_stage_yolo.py,
                                  twimo/strategies_eaf/two_stage_yolo_improved.py
        'none'  — Sensor data only, no perception
    """
    name: str
    extractor: str   # 'torch' | 'eaf' | 'yolo' | 'none'
    sample_hz: float


@dataclass
class ControlService:
    """Bridges a predicted maneuver class to vehicle control commands (steer + velocity).

    DTE Mapping: model.aiBasedServices.PlanningService (partially)
    PNG Layer: Digital Twin → Control Commands Regressor + Maneuver to Control Commands

    Current implementation (open-loop):
        twimo/dt/simulator.py feeds ground-truth steer_angle + velocity (from CSV) into
        the kinematic bicycle model — no prediction involved in the control path.

    Closed-loop (NOT YET IMPLEMENTED — future work):
        A regression model would predict steer + velocity from the maneuver class,
        enabling: ManeuverPredictor → ControlService → VehicleDT → DTComparator.
    """
    name: str
    regressor_type: str  # 'ground_truth' | 'kinematic' | 'ml_regressor' (future)
    input_type: str      # 'ground_truth_sensors' | 'predicted_maneuver'


# ------------------------------------------------------------
# Driving Behaviour
# ------------------------------------------------------------

@dataclass
class DrivingModel:
    """Core predictive model for driver behaviour.

    DTE Mapping: drivingBehaviour.DrivingModel
    PNG Layer: Digital Twin → Driver Behaviour DT (AI Service)
    Implementation: twimo/models/ (transformer, xgboost, gru, lstm, tcn, rf, mlp, ...)

    Tasks:
        'maneuver' — predict driver actions (TURN_LEFT, BRAKE, ...)
                     twimo/models/maneuver_transformer.py + baseline_window.py + ...
        'style'    — cluster driving styles (K-means)
                     twimo/models/style.py
        'explain'  — generate textual explanations
                     twimo/xai/explain.py
    """
    name: str
    task: str        # 'maneuver' | 'style' | 'explain'
    model_type: str  # 'transformer' | 'xgboost' | 'kmeans' | 'gru' | 'lstm' | 'tcn' | ...
    params: Dict[str, str] = field(default_factory=dict)


# ------------------------------------------------------------
# Visualization  (new concept per PNG VM02 architecture)
# ------------------------------------------------------------

@dataclass
class VisualizationService:
    """Renders predictions and explanations as annotated video or JSON reports.

    DTE Mapping: (new concept per PNG VM02 architecture — not in original metamodel)
    PNG Layer: Digital Twin → Video Annotation Renderer / Data Visualization (AI Service)
    Implementation:
        twimo/plots/annotate_video_eaf_yolo.py          — EAF + YOLO video annotation
        twimo/plots/annotate_video_eaf_yolo_improved.py — improved pipeline
        twimo/plots/annotate_video_eaf.py               — EAF-only annotation
        twimo/plots/annotate_video.py                   — basic annotation
    """
    name: str
    renderer: str       # 'video_annotator' | 'dashboard'
    output_format: str  # 'mp4' | 'json' | 'html'


# ------------------------------------------------------------
# Digital Twin (design-time assembly)
# ------------------------------------------------------------

@dataclass
class DigitalTwin:
    """Complete Digital Twin assembly — dataset + perception + driving model.

    DTE Mapping: digitalTwin.DigitalTwin
    PNG Layer: Digital Twin (Executable Models) layer
    Implementation: assembled by cli.py commands (train-maneuver, simulate-dt, explain).
                    Serialized as twin_config.json in each command's outdir.
    """
    name: str
    physical_system: str   # e.g. "Vehicle + Driver"
    dataset: Dataset
    perception: PerceptionService
    driving_model: DrivingModel


# ------------------------------------------------------------
# Factory function
# ------------------------------------------------------------

def instantiate_hdd_driving_behavior_twin(
    root: str,
    sample_hz: float = 3.0,
    extractor: str = "torch",
) -> DigitalTwin:
    """Pre-configured DigitalTwin for Honda Driving Dataset (HDD).

    DTE Mapping: digitalTwin.DigitalTwin wrapping HDD-specific components.
    Called from: twimo/cli.py at entry of train-maneuver and simulate-dt commands.
                 Output serialized to <outdir>/twin_config.json.
    """
    ds = Dataset(
        name="Honda HDD session bundle",
        sources=[
            DataSource(name="front_camera", modality="video", path=str(root)),
            DataSource(name="can_bus", modality="sensors", path=str(root)),
            DataSource(name="actions", modality="labels", path=str(root)),
        ],
    )
    perception = PerceptionService(name="PerceptionService", extractor=extractor, sample_hz=sample_hz)
    model = DrivingModel(name="DrivingBehaviorModel", task="maneuver", model_type="transformer")
    return DigitalTwin(
        name="DrivingBehaviorTwin",
        physical_system="Vehicle + Driver",
        dataset=ds,
        perception=perception,
        driving_model=model,
    )
